---
title: "Set up"
---

For this analysis (and coding in general) you will need to ensure you computer has a few things installed.

This will depend on your operating system and of course what interfaces you intend to use.

The documentation below is largely from [Software Carpentry](https://software-carpentry.org)

## Bash

The Bash Shell
Bash is a commonly-used shell that gives you the power to do simple tasks more quickly.

**Windows**

[Video Tutorial](https://www.youtube.com/watch?v=339AEqk9c-8)

1. Download the Git for Windows installer.
2. Run the installer and follow the steps bellow:
    a) Click on "Next".
    b) Click on "Next".
    c) Keep "Use Git from the Windows Command Prompt" selected and click on "Next". If you forgot to do this programs that you need for the workshop will not work properly. If this happens rerun the installer and select the appropriate option.
    d) Click on "Next".
    e) Keep "Checkout Windows-style, commit Unix-style line endings" selected and click on "Next".
    f) Keep "Use Windows' default console window" selected and click on "Next".
    g) Click on "Install".
    h) Click on "Finish".
3. If your "HOME" environment variable is not set (or you don't know what this is):
    a) Open command prompt (Open Start Menu then type `cmd` and press [Enter])
    b) Type the following line into the command prompt window exactly as shown:
`setx HOME "%USERPROFILE%"`
    c) Press [Enter], you should see 1SUCCESS: Specified value was saved.1
    d) Quit command prompt by typing `exit` then pressing [Enter]

This will provide you with both Git and Bash in the Git Bash program.

**macOS**

The default shell in all versions of macOS is Bash, so no need to install anything. You access Bash from the Terminal (found in `/Applications/Utilities`). See the Git installation [video tutorial](https://www.youtube.com/watch?v=9LQhwETCdwY) for an example on how to open the Terminal. You may want to keep Terminal in your dock for this workshop.

***

## Git

Git is a version control system that lets you track who made changes to what when and has options for easily updating a shared or public version of your code on [github.com](https://github.com/). You will need a [supported](https://help.github.com/articles/supported-browsers/) web browser (current versions of Chrome, Firefox or Safari, or Internet Explorer version 9 or above).

You will need an account at [github.com](https://github.com/) for parts of the Git lesson. Basic GitHub accounts are free. We encourage you to create a GitHub account if you don't have one already. Please consider what personal information you'd like to reveal. For example, you may want to review these [instructions for keeping your email address private](https://help.github.com/articles/keeping-your-email-address-private/) provided at GitHub.

**Windows**

Git should be installed on your computer as part of your Bash install (described above).

**macOS**

[Video Tutorial](https://www.youtube.com/watch?v=9LQhwETCdwY)
For OS X 10.9 and higher, install Git for Mac by downloading and running the most recent "mavericks" installer from [this list]. After installing Git, there will not be anything in your `/Applications` folder, as Git is a command line program. For older versions of OS X (10.5-10.8) use the most recent available installer labelled "snow-leopard" available [here](http://sourceforge.net/projects/git-osx-installer/files/).

***

## Text Editor

When you're writing code, it's nice to have a text editor that is optimized for writing code, with features like automatic color-coding of key words. The default text editor on macOS and Linux is usually set to Vim, which is not famous for being intuitive. if you accidentally find yourself stuck in it, try typing the escape key, followed by `:q!` (colon, lower-case 'q', exclamation mark), then hitting Return to return to the shell.

**Windows**

[Video Tutorial](https://www.youtube.com/watch?v=339AEqk9c-8)
nano is a basic editor and the default that instructors use in the workshop. To install it, download the [Software Carpentry Windows installer](https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe) and double click on the file to run it. This installer requires an active internet connection.

Others editors that you can use are [Notepad++](http://notepad-plus-plus.org/), [atom](https://atom.io/) or [Sublime Text](http://www.sublimetext.com/). Be aware that you must add its installation directory to your system path. Please ask your instructor to help you do this.

**macOS**

nano is a basic editor and the default that instructors use in the workshop. See the Git installation [video tutorial](https://www.youtube.com/watch?v=9LQhwETCdwY) for an example on how to open nano. It should be pre-installed.

Others editors that you can use are [Text Wrangler](http://www.barebones.com/products/textwrangler/), [atom](https://atom.io/) or [Sublime Text](http://www.sublimetext.com/).

***

## R

[R](http://www.r-project.org/) is a programming language that is especially powerful for data exploration, visualization, and statistical analysis. To interact with R, we use [RStudio](http://www.rstudio.com/).

**Windows**

[Video Tutorial](https://www.youtube.com/watch?v=q0PjTAylwoU)
Install R by downloading and running [this .exe file](http://cran.r-project.org/bin/windows/base/release.htm) from [CRAN](http://cran.r-project.org/index.html). Also, please install the [RStudio IDE](http://www.rstudio.com/ide/download/desktop). Note that if you have separate user and admin accounts, you should run the installers as administrator (right-click on .exe file and select "Run as administrator" instead of double-clicking). Otherwise problems may occur later, for example when installing R packages.

**macOS**

[Video Tutorial](https://www.youtube.com/watch?v=5-ly3kyxwEg)
Install R by downloading and running [this .pkg file](http://cran.r-project.org/bin/macosx/R-latest.pkg) from [CRAN](http://cran.r-project.org/index.html). Also, please install the [RStudio IDE](http://www.rstudio.com/ide/download/desktop).

***

## Anaconda - Jupyter notebook

Although Jupyter notebook is not neccessary to run the NGS analysis outlined in this webpage it is a very useful, easy to use and well documented tool.

It combines all the tools above - such as Bash and R and includes a lot more. It is great if you are interested in python scripting. In addition it also gives you an anaconda environment which is a common requirement for some program (in this case QIIME2). It can serve as a 'one stop shop' in respect to being able to execute Bash and Python code, it allows easy install of dependencies (which is partiuclarly prevelent in Python language) it allows you to use markdown with ease, and integrates with github. RStudio and a number of other programs are also integrates into the anaconda environment. 

For download of Anconda - Jupyter notebook click [here](http://jupyter.org/install).

A good (but perhaps long) video tutorial is available [here](https://www.youtube.com/watch?v=CwFq3YDU6_Y). 

***

## USEARCH

To do this analysis you will need to install USEARCH. This step has already been done if you are using the Cryptick Lab iMac - here 64-bit versions of the latest USEARCH 8, 9 and 10 packages have already been downloaded and installed in the path so you can skip this step.

For the purpose of this workflow we will assume the free 32-bit versions are sufficent (usually okay for 1-2 illumina MiSeq runs, depending on the amount of data generated).

The script in this workflow uses all three USEARCH versions so they will all need to be installed locally if you wish to use this workflow exactly how it appears. It can be tailored to the version you have - however you need to do this carefully, as some features do change between versions.
For example some points of different are: USEARCH v8 has a command to strip primers, that is not available in subsequent versions, and it does not have UNOISE commands, only UPARSE. USEARCH v9 has UNOISE2 and USEARCH v10 has UNOISE3.

The following instructions are for a MacOS or linux operating system. For details on a windows operating system see [USEARCH documentation](https://www.drive5.com/usearch/manual/problems_running.html).

**Download USEARCH**

To download USEARCH go to the [download page](https://www.drive5.com/usearch/download.html) and select the appriate platform and version number. You will then be sent a download link to your email. 

Save the file in an easy to locate path that you will not touch. I suggest adding a new folder in your home directory called `Programs`, you can rename the file to something easier e.g. `usearch9.2.34bit` this will let you know it is version 9.2 32-bit. 

**Execute permissions**

Once you have moved and saved it where you will not touch the file or any parent folders (i.e. the path) you will need to ensure that you have read and execute permissions for the binary file.

Within the Bash evironment (terminal for MacOS or your Git Bash for Windows) nagive to the directory:

```
cd /Users/username/Programs
```

You will then need to use the `chmod` command to ensure you have read and execute permissions for the binary file. If you have multiple binary files (i.e. downloaded multiple USEARCH versions) you will need to do this for each.

```
chmod +x usearch9.2.32bit
```

**Updaing path**

To avoid refering to the complete path everything you want to execute a usearch command you can update your path using the Bash environment.

Navigate to your home directory by running opening up a new terminal window, and do the following:
```
cd ~
```

To edit your path, you need need to open the `.bash_profile` in a text editor, such as the following: 
```
vi .bash_profile
```

This opens up a text editor (in this case vi) to edit your path. It is **very** important you *add* to your path, and  *do **not** delete it!*. 

Currently your path may look something like:

```
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

To update your path add to it by using a semi-colon to seperate and add the new location, such as the example below:
```
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/username/Programs"
```

To check your path you can use the following command `echo $PATH`.

For more detailed information on updating the path environment see [here](https://stackoverflow.com/questions/22465332/setting-path-environment-variable-in-osx-permanently)

***